Repository hhu-propra2/abschlussprojekt-bugrog-morgoth-ush-parse, pull requests merged in 2019-02, with the labels that each got.

#49 Models: item and user
  src/main/java/de/hhu/propra/sharingplatform/model/Item.java
  src/main/java/de/hhu/propra/sharingplatform/model/User.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: required

#61 Add DAO Repos to entities
  src/main/java/de/hhu/propra/sharingplatform/modelDAO/ContractRepo.java
  src/main/java/de/hhu/propra/sharingplatform/modelDAO/ItemRepo.java
  src/main/java/de/hhu/propra/sharingplatform/modelDAO/OfferRepo.java
  src/main/java/de/hhu/propra/sharingplatform/modelDAO/UserRepo.java
Labels: required

#65 Faker for item and users
  src/main/java/de/hhu/propra/sharingplatform/faker/DataFaker.java
  src/main/java/de/hhu/propra/sharingplatform/faker/ItemFaker.java
  src/main/java/de/hhu/propra/sharingplatform/faker/UserFaker.java
  src/main/java/de/hhu/propra/sharingplatform/model/Item.java
Labels: verify

#71 Faker Test and add missing fields in faker
  src/main/java/de/hhu/propra/sharingplatform/faker/ItemFaker.java
  src/main/java/de/hhu/propra/sharingplatform/faker/UserFaker.java
  src/main/java/de/hhu/propra/sharingplatform/model/Item.java
  src/main/java/de/hhu/propra/sharingplatform/model/User.java
  src/test/java/de/hhu/propra/sharingplatform/faker/ItemFakerTest.java
  src/test/java/de/hhu/propra/sharingplatform/faker/UserFakerTest.java
Labels: required, verify

#97 Fix Faker tests and performance of other tests
  src/main/java/de/hhu/propra/sharingplatform/faker/ItemFaker.java
  src/main/java/de/hhu/propra/sharingplatform/faker/UserFaker.java
  src/main/java/de/hhu/propra/sharingplatform/model/Item.java
  src/test/java/de/hhu/propra/sharingplatform/faker/ItemFakerTest.java
  src/test/java/de/hhu/propra/sharingplatform/faker/UserFakerTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/ContractServiceTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/OfferServiceTest.java
Labels: required, verify

#115 Base html layout
  build.gradle
  src/main/resources/static/css/items.css
  src/main/resources/templates/account.html
  src/main/resources/templates/base.html
  src/main/resources/templates/details.html
  src/main/resources/templates/itemForm.html
  src/main/resources/templates/mainpage.html
  src/main/resources/templates/register.html
Labels: required

#135 User account details
  src/main/resources/static/css/footer.css
  src/main/resources/templates/account.html
  src/main/resources/templates/base.html
  src/main/resources/templates/details.html
Labels: required, verify

#149 Faker refactor
  src/main/java/de/hhu/propra/sharingplatform/faker/DataFaker.java
  src/main/java/de/hhu/propra/sharingplatform/faker/UserFaker.java
  src/main/java/de/hhu/propra/sharingplatform/model/Item.java
  src/main/java/de/hhu/propra/sharingplatform/model/Offer.java
  src/main/java/de/hhu/propra/sharingplatform/service/OfferService.java
  src/main/resources/banner.txt
  src/test/java/de/hhu/propra/sharingplatform/service/OfferServiceTest.java
Labels: required, verify

#158 Offer request page
  src/main/java/de/hhu/propra/sharingplatform/faker/DataFaker.java
  src/main/resources/templates/account.html
Labels: required, verify

#163 Search bar
  src/main/java/de/hhu/propra/sharingplatform/controller/SharingPlatformController.java
  src/main/java/de/hhu/propra/sharingplatform/dao/ItemRepo.java
  src/main/java/de/hhu/propra/sharingplatform/service/ItemService.java
  src/main/resources/templates/base.html
  src/main/resources/templates/mainpage.html
  src/test/java/de/hhu/propra/sharingplatform/service/ItemServiceTest.java
Labels: verify

#225 Tests for BorrowContract and sub classes
  src/main/java/de/hhu/propra/sharingplatform/model/contracts/SellContract.java
  src/main/java/de/hhu/propra/sharingplatform/model/payments/Payment.java
  src/main/java/de/hhu/propra/sharingplatform/service/payment/ProPayApi.java
  src/test/java/de/hhu/propra/sharingplatform/model/BorrowContractPaymentTest.java
  src/test/java/de/hhu/propra/sharingplatform/model/contracts/SellContractTest.java
Labels: Wait for other Branch

#230 Contract-Sale and recommend fix
  src/main/java/de/hhu/propra/sharingplatform/controller/ContractController.java
  src/main/java/de/hhu/propra/sharingplatform/controller/ItemSaleController.java
  src/main/java/de/hhu/propra/sharingplatform/model/User.java
  src/main/java/de/hhu/propra/sharingplatform/model/contracts/Contract.java
  src/main/java/de/hhu/propra/sharingplatform/model/contracts/SellContract.java
  src/main/java/de/hhu/propra/sharingplatform/model/items/Item.java
  src/main/java/de/hhu/propra/sharingplatform/model/payments/Payment.java
  src/main/java/de/hhu/propra/sharingplatform/service/ApiService.java
  src/main/java/de/hhu/propra/sharingplatform/service/ContractService.java
  src/main/java/de/hhu/propra/sharingplatform/service/RecommendationService.java
  src/main/java/de/hhu/propra/sharingplatform/service/payment/IPaymentService.java
  src/main/java/de/hhu/propra/sharingplatform/service/payment/PaymentService.java
  src/main/java/de/hhu/propra/sharingplatform/service/payment/ProPayApi.java
  src/main/java/de/hhu/propra/sharingplatform/service/validation/ItemValidator.java
  src/main/resources/templates/account.html
  src/main/resources/templates/itemSaleDetails.html
  src/test/java/de/hhu/propra/sharingplatform/faker/UserFakerTest.java
  src/test/java/de/hhu/propra/sharingplatform/model/contracts/SellContractTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/RecommendationServiceTest.java
Labels: Primary Branch

#228 Image refactor
  .gitignore
  Dockerfile
  docker-compose.yml
  public/images/dummy
  src/main/java/de/hhu/propra/sharingplatform/config/ResourceConfig.java
  src/main/java/de/hhu/propra/sharingplatform/model/items/Item.java
  src/main/java/de/hhu/propra/sharingplatform/security/SecConfig.java
  src/main/java/de/hhu/propra/sharingplatform/service/ImageService.java
  src/main/java/de/hhu/propra/sharingplatform/service/ItemService.java
  src/main/java/de/hhu/propra/sharingplatform/service/ResourceConfig.java
  src/main/resources/static/css/account.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/items.css
  src/main/resources/static/css/register.css
  src/main/resources/static/images/Header.png
  src/main/resources/static/images/dummy.png
  src/main/resources/templates/itemDetails.html
  src/main/resources/templates/itemSaleDetails.html
  src/main/resources/templates/mainpage.html
  src/main/resources/templates/salepage.html
  src/test/java/de/hhu/propra/sharingplatform/controller/ItemRentalControllerTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/ItemRentalServiceTest.java
  static/images/Logo_Square_small.png
  static/images/OneDoesNotSimplyJens.png
  static/images/dummy.png
Labels: Primary Branch

#227 Docker prod
  Dockerfile
  docker-compose.yml
  src/main/java/de/hhu/propra/sharingplatform/faker/DataFaker.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/test/java/de/hhu/propra/sharingplatform/SharingplatformApplicationTests.java
  src/test/java/de/hhu/propra/sharingplatform/dao/ConflictRepoTest.java
Labels: Primary Branch

#243 Test for different Classes
  src/main/java/de/hhu/propra/sharingplatform/controller/ItemSaleController.java
  src/main/java/de/hhu/propra/sharingplatform/faker/UserFaker.java
  src/main/java/de/hhu/propra/sharingplatform/model/User.java
  src/main/java/de/hhu/propra/sharingplatform/service/ConflictService.java
  src/main/resources/templates/account.html
  src/test/java/de/hhu/propra/sharingplatform/controller/ContractControllerTest.java
  src/test/java/de/hhu/propra/sharingplatform/controller/ItemRentalControllerTest.java
  src/test/java/de/hhu/propra/sharingplatform/controller/ItemSaleControllerTest.java
  src/test/java/de/hhu/propra/sharingplatform/faker/ItemSaleFakerTest.java
  src/test/java/de/hhu/propra/sharingplatform/faker/UserFakerTest.java
  src/test/java/de/hhu/propra/sharingplatform/model/items/ItemRentalTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/ConflictServiceTest.java
Labels: Primary Branch

#251 ProPay Host Properties
  src/main/java/de/hhu/propra/sharingplatform/service/payment/ProPayApi.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/test/java/de/hhu/propra/sharingplatform/service/RecommendationServiceTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/payment/ProPayApiTest.java
Labels: Primary Branch, required

#256 Searchbar Bug Fix
  src/main/java/de/hhu/propra/sharingplatform/controller/SharingPlatformController.java
  src/main/java/de/hhu/propra/sharingplatform/dao/ItemRentalRepo.java
  src/main/java/de/hhu/propra/sharingplatform/dao/ItemRepo.java
  src/main/java/de/hhu/propra/sharingplatform/dao/ItemSaleRepo.java
  src/main/java/de/hhu/propra/sharingplatform/service/ItemService.java
  src/main/resources/templates/base.html
  src/test/java/de/hhu/propra/sharingplatform/controller/SharingPlatformControllerTest.java
  src/test/java/de/hhu/propra/sharingplatform/service/ItemRentalServiceTest.java
Labels: Primary Branch
